apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: fotos
  name: fotos
spec:
  containers:
  - image: vicente/fotos-image:1.0
    name: fotos
    resources: {}
    volumeMounts:
    - mountPath: /fotos
      name: fotos
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: fotos
    hostPath:
      path: /c/Users/vegav/Downloads/fotos
status: {}
